##############################################################################
# Automations to set colors on HASP Page 1
#
# Here we've swapped selected/unselected as these buttons will always be
# unselected (unless actively being pressed).
automation:
  - alias: hasp_tower_p1_ColorConfig
    trigger:
    - platform: state
      entity_id: 'binary_sensor.tower_connected'
      to: 'on'
    - platform: homeassistant
      event: start
    - platform: state
      entity_id: input_number.hasp_tower_selectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_tower_unselectedbackgroundcolor
    - platform: state
      entity_id: input_number.hasp_tower_selectedforegroundcolor
    - platform: state
      entity_id: input_number.hasp_tower_unselectedforegroundcolor
    action:
    - service: mqtt.publish
      data:
        topic: 'hasp/tower/command/json'
        payload_template: >-
          [{%- for i in range(4,8) -%}"p[1].b[{{i}}].pco={{ states.input_number.hasp_tower_selectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,8) -%}"p[1].b[{{i}}].bco={{ states.input_number.hasp_tower_selectedbackgroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,8) -%}"p[1].b[{{i}}].pco2={{ states.input_number.hasp_tower_unselectedforegroundcolor.state|int }}",{%- endfor -%}
          {%- for i in range(4,8) -%}"p[1].b[{{i}}].bco2={{ states.input_number.hasp_tower_unselectedbackgroundcolor.state|int }}",{%- endfor -%}]